-- Run once in Supabase Dashboard > SQL Editor.
create table if not exists public.documents (
  id uuid primary key, name text not null, file_type text not null,
  size bigint not null, status text not null, department text not null,
  content text not null, path text not null, created_at timestamptz not null
);

create table if not exists public.chunks (
  id uuid primary key, document_id uuid not null references public.documents(id) on delete cascade,
  chunk_index integer not null, content text not null, vector text not null,
  vector_model text not null, created_at timestamptz not null
);
create index if not exists idx_chunks_document on public.chunks(document_id);

create table if not exists public.messages (
  id bigint generated by default as identity primary key, conversation_id uuid not null,
  role text not null, content text not null, created_at timestamptz not null
);

create table if not exists public.query_logs (
  id bigint generated by default as identity primary key, question text not null,
  successful integer not null, latency_ms integer not null, created_at timestamptz not null
);

create table if not exists public.comparisons (
  id uuid primary key, document_a_id uuid not null references public.documents(id) on delete cascade,
  document_b_id uuid not null references public.documents(id) on delete cascade,
  document_a_name text not null, document_b_name text not null,
  comparison text not null, configured integer not null, created_at timestamptz not null
);

alter table public.documents enable row level security;
alter table public.chunks enable row level security;
alter table public.messages enable row level security;
alter table public.query_logs enable row level security;
alter table public.comparisons enable row level security;

-- Private bucket. The FastAPI backend uses the service-role key and bypasses RLS.
insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do update set public = false;
