import { FormEvent, useEffect, useState } from 'react'
import { CheckCircle2, Circle, Network, SearchCheck, ShieldAlert } from 'lucide-react'
import { AgentRisk, AgentRun, analyzeRisks, DocumentItem, getAgentRuns, getInsights, getKnowledgeMap, Insight, KnowledgeMap as MapData, research, ResearchResult, submitReview } from '../services/api'

export function ResearchPage({documents}:{documents:DocumentItem[]}){
 const [question,setQuestion]=useState(''),[result,setResult]=useState<ResearchResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const run=async(e:FormEvent)=>{e.preventDefault();if(!question.trim())return;setBusy(true);setError('');try{setResult(await research(question))}catch(err){setError(err instanceof Error?err.message:'Research failed')}finally{setBusy(false)}}
 return <section className="agent-grid"><form className="agent-card agent-prompt" onSubmit={run}><SearchCheck/><h2>AI Research Agent</h2><p>Plans, retrieves, analyzes, verifies, and critiques evidence from {documents.length} indexed documents.</p><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask a complex research question…"/><button className="primary" disabled={busy||!question.trim()}>{busy?'Running bounded research…':'Start research'}</button>{error&&<div className="error-box">{error}</div>}</form>{result&&<><article className="agent-card"><h2>Execution timeline</h2><div className="timeline">{result.plan.map(step=><div key={step.order}><CheckCircle2/><span><strong>{step.name}</strong><small>{step.status}</small></span></div>)}</div></article><article className="agent-card agent-output"><div className="output-head"><h2>Verified answer</h2><span className={result.critic.passed?'verified':'weak'}>Critic {Math.round(result.critic.score*100)}%</span></div><p>{result.answer}</p>{result.evidence.map((item,i)=><details className="citation" key={item.chunk_id}><summary>[Source {i+1}] {item.document_name} · {item.verified?'Verified citation':'Weak evidence'}</summary><p>{item.excerpt}</p></details>)}</article>{result.risks.length>0&&<RiskList risks={result.risks} runId={result.run_id} disclaimer={result.disclaimer}/>}</>}</section>
}

function RiskList({risks,runId,disclaimer}:{risks:AgentRisk[];runId?:string;disclaimer?:string}){return <article className="agent-card agent-output"><h2>Risk findings</h2>{risks.map((risk,i)=><div className="risk-row" key={i}><span className={`severity ${risk.severity.toLowerCase()}`}>{risk.severity}</span><div><strong>{risk.title}</strong><p>{risk.description}</p><small>Evidence: {risk.evidence}</small>{runId&&<div className="review-actions"><button onClick={()=>submitReview(runId,'approve')}>Approve</button><button onClick={()=>submitReview(runId,'reject')}>Reject</button><button onClick={()=>submitReview(runId,'request_reanalysis')}>Request re-analysis</button></div>}</div></div>)}<p className="disclaimer">{disclaimer}</p></article>}

export function RiskPage({documents}:{documents:DocumentItem[]}){const [risks,setRisks]=useState<AgentRisk[]>([]),[busy,setBusy]=useState(false);const run=async()=>{setBusy(true);try{setRisks((await analyzeRisks('risk penalty obligation deadline contradiction compliance',documents.map(d=>d.id))).risks)}finally{setBusy(false)}};return <section className="agent-grid"><article className="agent-card agent-prompt"><ShieldAlert/><h2>AI Risk & Compliance Analyst</h2><p>Scans grounded document evidence for obligations and potential concerns.</p><button className="primary" onClick={run} disabled={busy||!documents.length}>{busy?'Analyzing…':'Analyze all documents'}</button></article>{risks.length?<RiskList risks={risks} disclaimer="AI risk analysis assists human review and is not legal or compliance advice."/>:<article className="agent-card empty-agent"><Circle/><p>No risk analysis has been run.</p></article>}</section>}

export function InsightsPage(){const [items,setItems]=useState<Insight[]>([]);useEffect(()=>{getInsights().then(setItems)},[]);return <section className="agent-card"><h2>AI Executive Insights</h2><p>Every insight below is linked to document evidence.</p><div className="insight-list">{items.map((item,i)=><article key={i}><span className={`severity ${item.severity.toLowerCase()}`}>{item.severity}</span><div><small>{item.category} · {item.document_name}</small><h3>{item.title}</h3><p>{item.description}</p><details><summary>View evidence</summary>{item.evidence}</details></div></article>)}{!items.length&&<p>No evidence-backed insights are available yet.</p>}</div></section>}

export function RunsPage(){const [runs,setRuns]=useState<AgentRun[]>([]);useEffect(()=>{getAgentRuns().then(setRuns)},[]);return <section className="agent-card"><h2>Agent Execution</h2><p>Safe operational metadata only. Private reasoning is never displayed.</p><div className="run-table"><div className="run-head"><b>Agent</b><b>Status</b><b>Steps</b><b>Retrievals</b><b>Evidence</b><b>Critic</b><b>Latency</b></div>{runs.map(run=><div key={run.id}><span>{run.agent_type}</span><span>{run.status}</span><span>{run.steps}</span><span>{run.retrieval_attempts}</span><span>{run.evidence_count}</span><span>{Math.round(run.critic_score*100)}%</span><span>{run.latency_ms} ms</span></div>)}</div></section>}

export function MapPage(){const [map,setMap]=useState<MapData>({nodes:[],links:[]});useEffect(()=>{getKnowledgeMap().then(setMap)},[]);const connected=(id:string)=>map.links.filter(l=>l.source===id).map(l=>map.nodes.find(n=>n.id===l.target)).filter(Boolean);return <section className="agent-card"><h2><Network/> Knowledge Map</h2><p>Lightweight relationships derived from document intelligence metadata.</p><div className="knowledge-map">{map.nodes.filter(n=>n.type==='document').map(doc=><article key={doc.id}><strong>{doc.label}</strong>{connected(doc.id).map(node=><span className={`map-${node?.type}`} key={node?.id}>{node?.label}</span>)}</article>)}{!map.nodes.length&&<p>Upload and analyze documents to build the knowledge map.</p>}</div></section>}
