import { FormEvent, useEffect, useRef, useState } from 'react'
import { ArrowRight, Bot, CheckCircle2, Eye, FileCheck2, FileText, GitCompare, MessageSquareText, Search, Send, Sparkles, Trash2, Upload, X } from 'lucide-react'
import { MetricCard } from './components/MetricCard'
import { PageName, Sidebar } from './components/Sidebar'
import { Analytics, askQuestion, ChatResult, compareDocuments, deleteDocument, DocumentDetail, DocumentItem, getAnalytics, getDocument, listDocuments, uploadDocument } from './services/api'
import { useHealth } from './hooks/useHealth'
import { InsightsPage, MapPage, ResearchPage, RiskPage, RunsPage } from './components/AgentPages'

function Header({title,onUpload}:{title:string;onUpload:()=>void}){return <header className="topbar"><div><p className="eyebrow">ENTERPRISE KNOWLEDGE</p><h1>{title}</h1><p>Search, understand, and govern your organization’s knowledge.</p></div><div className="top-actions"><button className="search-btn"><Search size={18}/><span>Search anything</span></button><button onClick={onUpload} className="primary"><Upload size={17}/>Upload document</button></div></header>}

function UploadDialog({close,done}:{close:()=>void;done:()=>void}){
 const [file,setFile]=useState<File|null>(null),[department,setDepartment]=useState('General'),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!file)return;setBusy(true);setError('');try{await uploadDocument(file,department);done();close()}catch(err){setError(err instanceof Error?err.message:'Upload failed')}finally{setBusy(false)}}
 return <div className="modal-backdrop" onMouseDown={close}><form className="modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="modal-close" onClick={close}><X/></button><h2>Upload document</h2><p>PDF, DOCX, TXT or Markdown · maximum 20 MB</p><label className="drop-zone"><Upload/><strong>{file?.name ?? 'Choose a document'}</strong><span>Click to browse your computer</span><input type="file" accept=".pdf,.docx,.txt,.md" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label className="field">Department<input value={department} onChange={e=>setDepartment(e.target.value)}/></label>{error&&<div className="error-box">{error}</div>}<button className="primary modal-submit" disabled={!file||busy}>{busy?'Extracting and indexing…':'Upload and index'}</button></form></div>
}

function Documents({items,reload}:{items:DocumentItem[];reload:()=>void}){
 const [query,setQuery]=useState(''),[detail,setDetail]=useState<DocumentDetail|null>(null);const filtered=items.filter(d=>d.name.toLowerCase().includes(query.toLowerCase()))
 return <><section className="page-panel"><div className="toolbar"><div className="filter-input"><Search size={17}/><input placeholder="Search documents" value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{filtered.length} documents · {items.reduce((n,d)=>n+d.chunk_count,0)} chunks</span></div>{!filtered.length?<div className="empty"><FileText/><h2>No documents found</h2><p>Upload a policy or handbook to make it searchable.</p></div>:<div className="document-list">{filtered.map(doc=><div className="document-row" key={doc.id}><span className="file-icon"><FileText/></span><div><strong>{doc.name}</strong><small>{doc.department} · {doc.chunk_count} chunks · {doc.vector_model??'Index pending'}</small></div><span className="type">{doc.file_type}</span><span className="badge indexed">{doc.status}</span><button className="view-chunks" onClick={async()=>setDetail(await getDocument(doc.id))}><Eye size={15}/> Chunks</button><button className="icon-danger" title="Delete" onClick={async()=>{if(confirm(`Delete ${doc.name}?`)){await deleteDocument(doc.id);reload()}}}><Trash2 size={17}/></button></div>)}</div>}</section>{detail&&<div className="modal-backdrop" onMouseDown={()=>setDetail(null)}><div className="modal chunk-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setDetail(null)}><X/></button><h2>{detail.name}</h2><p>{detail.chunks.length} indexed chunks · {detail.vector_model}</p><div className="chunk-list">{detail.chunks.map(c=><article key={c.id}><strong>Chunk {c.chunk_index+1}</strong><span>{c.vector_model}</span><p>{c.content}</p></article>)}</div></div></div>}</>
}

function Compare({documents}:{documents:DocumentItem[]}){
 const [first,setFirst]=useState(''),[second,setSecond]=useState(''),[firstDetail,setFirstDetail]=useState<DocumentDetail|null>(null),[secondDetail,setSecondDetail]=useState<DocumentDetail|null>(null),[result,setResult]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let active=true;if(!first){setFirstDetail(null);return}getDocument(first).then(value=>{if(active)setFirstDetail(value)}).catch(err=>setError(err instanceof Error?err.message:'Could not load Document A'));return()=>{active=false}},[first])
 useEffect(()=>{let active=true;if(!second){setSecondDetail(null);return}getDocument(second).then(value=>{if(active)setSecondDetail(value)}).catch(err=>setError(err instanceof Error?err.message:'Could not load Document B'));return()=>{active=false}},[second])
 const run=async()=>{setError('');setResult('');setBusy(true);try{const value=await compareDocuments(first,second);setResult(value.comparison)}catch(err){setError(err instanceof Error?err.message:'Comparison failed')}finally{setBusy(false)}}
 const documentTable=(label:string,detail:DocumentDetail|null)=><article className="compare-document"><header><span>{label}</span><h2>{detail?.name??'Select a document above'}</h2></header>{detail&&<><table className="metadata-table"><tbody><tr><th>File type</th><td>{detail.file_type}</td></tr><tr><th>Department</th><td>{detail.department}</td></tr><tr><th>Size</th><td>{(detail.size/1024).toFixed(1)} KB</td></tr><tr><th>Status</th><td><span className="badge indexed">{detail.status}</span></td></tr><tr><th>Chunks</th><td>{detail.chunks.length}</td></tr><tr><th>Vector model</th><td>{detail.vector_model}</td></tr></tbody></table><div className="compare-chunks"><h3>Document chunks</h3><table><thead><tr><th>#</th><th>Chunk content</th><th>Vector</th></tr></thead><tbody>{detail.chunks.map(chunk=><tr key={chunk.id}><td>{chunk.chunk_index+1}</td><td>{chunk.content}</td><td>{chunk.vector_model}</td></tr>)}</tbody></table></div></>}</article>
 return <section className="compare-page"><div className="compare-controls"><div><label>Document A</label><select value={first} onChange={e=>{setFirst(e.target.value);setResult('')}}><option value="">Select a document</option>{documents.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div><GitCompare/><div><label>Document B</label><select value={second} onChange={e=>{setSecond(e.target.value);setResult('')}}><option value="">Select a document</option>{documents.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div><button className="primary" disabled={!first||!second||first===second||busy} onClick={run}>{busy?'Comparing…':'Compare documents'}</button></div>{error&&<div className="error-box">{error}</div>}<div className="comparison-tables">{documentTable('DOCUMENT A',firstDetail)}{documentTable('DOCUMENT B',secondDetail)}</div>{result&&<article className="comparison-result"><h2>Comparison analysis</h2><div>{result}</div></article>}</section>
}

function Assistant({documents}:{documents:DocumentItem[]}){
 const [question,setQuestion]=useState(''),[messages,setMessages]=useState<{role:'user'|'assistant';text:string;result?:ChatResult}[]>([]),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),end=useRef<HTMLDivElement>(null)
 // Avoid moving the entire page below the viewport when this tab first opens.
 useEffect(()=>{if(messages.length>0)end.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[messages])
 const send=async(e:FormEvent)=>{e.preventDefault();const text=question.trim();if(!text||busy)return;setQuestion('');setMessages(m=>[...m,{role:'user',text}]);setBusy(true);try{const result=await askQuestion(text,selected);setMessages(m=>[...m,{role:'assistant',text:result.answer,result}])}catch(err){setMessages(m=>[...m,{role:'assistant',text:err instanceof Error?err.message:'Request failed'}])}finally{setBusy(false)}}
 return <section className="chat-layout"><aside className="chat-filters"><h3>Document scope</h3><button className={!selected.length?'selected':''} onClick={()=>setSelected([])}>All documents</button>{documents.map(d=><button className={selected.includes(d.id)?'selected':''} onClick={()=>setSelected(s=>s.includes(d.id)?s.filter(id=>id!==d.id):[...s,d.id])} key={d.id}>{d.name}</button>)}</aside><div className="chat-main"><div className="messages">{!messages.length&&<div className="chat-empty"><span><Sparkles/></span><h2>Ask your knowledge base</h2><p>Answers are grounded in the documents you upload.</p>{['What are the key policies?','Summarize the uploaded documents','What are the important dates?'].map(q=><button key={q} onClick={()=>setQuestion(q)}>{q}<ArrowRight size={15}/></button>)}</div>}{messages.map((m,i)=><div className={`message ${m.role}`} key={i}><div className="message-avatar">{m.role==='user'?'You':<Bot size={18}/>}</div><div><strong>{m.role==='user'?'You':'Knowledge Assistant'}</strong><p>{m.text}</p>{m.result&&<><span className={`confidence ${m.result.confidence.toLowerCase()}`}>Evidence confidence: {m.result.confidence}</span>{m.result.citations.map((c,n)=><details className="citation" key={n}><summary>[Source {n+1}] {c.document_name}</summary><p>{c.excerpt}</p></details>)}</>}</div></div>)}{busy&&<div className="thinking">Searching documents and preparing an answer…</div>}<div ref={end}/></div><form className="chat-compose" onSubmit={send}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder={documents.length?'Ask a question about your documents…':'Upload a document before asking a question'} disabled={!documents.length}/><button disabled={!documents.length||busy}><Send size={18}/></button></form></div></section>
}

function Dashboard({stats,openAssistant}:{stats:Analytics;openAssistant:()=>void}){return <><section className="metrics"><MetricCard icon={FileText} label="Total documents" value={String(stats.total_documents)} note="Stored securely" tone="sage"/><MetricCard icon={FileCheck2} label="Indexed documents" value={String(stats.indexed_documents)} note="Ready to search" tone="blue"/><MetricCard icon={MessageSquareText} label="Questions asked" value={String(stats.total_queries)} note="All conversations" tone="violet"/><MetricCard icon={CheckCircle2} label="Successful answers" value={String(stats.successful_answers)} note={`${stats.average_response_time_ms} ms average`} tone="gold"/></section><article className="ask-card"><div><span className="spark"><Sparkles/></span><p>ENTERPRISE KNOWLEDGE ASSISTANT</p><h2>Your documents are ready for questions</h2><span>Upload documents, then get grounded answers with evidence.</span></div><button className="dashboard-ask" onClick={openAssistant}>Open AI Assistant <ArrowRight/></button></article></>}

export default function App(){
 const [page,setPage]=useState<PageName>('Dashboard'),[documents,setDocuments]=useState<DocumentItem[]>([]),[stats,setStats]=useState<Analytics>({total_documents:0,indexed_documents:0,total_queries:0,successful_answers:0,average_response_time_ms:0}),[uploader,setUploader]=useState(false);const {health,error}=useHealth()
 const reload=()=>{listDocuments().then(setDocuments).catch(()=>setDocuments([]));getAnalytics().then(setStats).catch(()=>undefined)};useEffect(reload,[])
 const content=page==='Dashboard'?<Dashboard stats={stats} openAssistant={()=>setPage('AI Assistant')}/>:page==='Documents'?<Documents items={documents} reload={reload}/>:page==='AI Assistant'?<Assistant documents={documents}/>:page==='Compare Documents'?<Compare documents={documents}/>:page==='AI Research'?<ResearchPage documents={documents}/>:page==='AI Insights'?<InsightsPage/>:page==='Risk Analysis'?<RiskPage documents={documents}/>:page==='Knowledge Map'?<MapPage/>:<RunsPage/>
 return <div className="app-shell"><Sidebar page={page} onChange={setPage}/><main><Header title={page} onUpload={()=>setUploader(true)}/><section className="status-banner"><span className={`pulse ${health?'online':error?'offline':''}`}/><div><strong>{health?'Backend connected':error?'Backend unavailable':'Connecting…'}</strong><small>{health?`API v${health.version} · ${documents.length} documents indexed`:error}</small></div></section>{content}</main>{uploader&&<UploadDialog close={()=>setUploader(false)} done={reload}/>}</div>
}
